version: '2'
services:
  web:
    build: .
    command: /usr/local/bin/start.sh
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    container_name: web

  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes_from:
      - mysql_data
    ports:
      - "6033:3306" #DB clientからの接続用
    container_name: db

  mysql_data:
    image: busybox
    volumes:
      - ./mysql_data:/var/lib/mysql
    container_name: mysql_data
