version: '2'
services:
  web: &web_base
    build: .
    command: /usr/local/bin/start.sh
    volumes:
      - .:/myapp:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    container_name: web
    tty: true
    stdin_open: true
  spring:
    <<: *web_base
    command: spring server
    ports: []
    pid: host
    environment:
      PATH: /myapp/bin:$PATH
      SPRING_SOCKET: /tmp/spring/spring.sock
    volumes:
      - .:/myapp:cached
      - spring:/tmp/spring
    container_name: spring
  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes_from:
      - mysql_data
    ports:
      - "6033:3306" #DB clientからの接続用
    container_name: db

  mysql_data:
    image: busybox
    volumes:
      - ./mysql_data:/var/lib/mysql:delegated
    container_name: mysql_data
volumes:
  spring: